apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-apache
  name: sample-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-apache
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-apache
    spec:
      containers:
      - image: pentalink/apache:test
        name: apache
        ports:
        - containerPort: 80
